export const CHANGE_SIGNAL_STRENGTH = "CHANGE_SIGNAL_STRENGTH";
export const CHANGE_CONNECTED_VALUE = "CHANGE_CONNECTED_VALUE";
export const CHANGE_MQTTBOOL_VALUE = "CHANGE_MQTTBOOL_VALUE";
export const CHANGE_MQTTBOOL_VALUE_ASYNC = "CHANGE_MQTTBOOL_VALUE_ASYNC";
export const CHANGE_CONNECTED_VALUE_ASYNC = "CHANGE_CONNECTED_VALUE_ASYNC";
